name: sqlite_drift_practice
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  drift: ^2.28.1
  sqlite3: ^2.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.7.0
  drift_dev: ^2.28.1
  lints: ^5.0.0
  test: ^1.24.0
